title: Comidas de Cantabria
description: Un blog donde subimos posts sobre las comidas tipicas de Cantabria, los ingredientes necesarios y la preparacion de las mismas.
author: Carlos Aguilar Hernández y Julián Sainz Rodríguez
avatar: /bandera.jfif
email: julian.sainzrodriguez@iesmiguelherrero.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: caguilarhernandez
  card: summary
facebook:
  username: caguilarhernandez
  card: summary
logo: bandera.jfif
social:
  name: Carlos Aguilar Hernández y Julián Sainz Rodríguez
  links:
    - https://www.twitter.com/caguilarheernandez
    - https://www.facebook.com/caguilarheernandez
    - https://github.com/caguilarhernandez
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: es
